# Generated by Django 2.2 on 2020-05-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
